language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "w8YXsZvXiN5fna6CrVWhkgrTINRXJCIqX/cKCeveGHAejg3x4T4h50BcIP93AxLvdCMOtR3+hVCRoiAg1Ybi2ivWUIHjMKEIYJVXvkKlef+rJwjDNRhRZreIXMco6kjuQLvCK7bWvKpT/o9l+7YplhSnUID7gosZi99C9rzVkqmAJt6xF5paDOAZQ7Fmd2tC1iAmo+Xub8VSfcyhXkwSHKKmJRQVe7eGROc2nE28+Ce8m2M8lXDKwu67WzQIxbAQo8cWlJKxk0jdrFD0Wg0QMgCG7rY21B8VMsJCpM6MqwgEJ7MhrWaCPknZKrQ0mU18lzdjJ5GV94qQJgHNhOla5TrVeyjLWVLCtJxRLa7p9Sfa/3JH8LoAM7ygYbXO351EQ1T0mz1/BG/xUh8YaT8syIUr13cl9inbLDDuaCwgAF/NwLoj/B5jRO0cByHXESmtJ19uNdol11YIDc0F5hqgjyCUYwpCH3ADLh/9A3CwztPrLfCAqdT3YMTv+pehfV0VyxbJTfTbVtL9ou2gBMUFCyuDnXlyPKsvdxMfFSaHBjRzfBECzll3ogxNBtSAbGz4v6Y+AuXiyOI52NfhBBMdlWBrbkhndrqlItUUV4ckX76LJhzBCdVMxz9dOrOja3P7LbFZmx0cDeWR1piiZsUx0SWxtHJMHFV6qDjIHma2vvk="
  secret_access_key:
    secure: "LJEDZGAPmerD6P1X43kX1+vQ6nm4NvjPnGwCxYo55PJdwpiCJjKu5rPyNKE5Siu1YOcNMhZJHigNnB2xiFUgQ4yuFeSSqGEw3PwmSagVXUWzWhrqxPgydmYGm3auqfFvDyehDVlZqEKGE+1sDf1Q1ljPzp5m0A30J5NchIEdcnz5X2nxqrmpCTIbG5++ccQAyxEZxU1QekCOV2PWy0D5talp+TQ9CU8E7yetjPm9vH8EqPCpns9Wtcca7yvV0g/p4xk3pT+crytPtqW9jU3inpf/zTxv7fahvUVXX16XT+wzNH8tQ1ArDutE5hy5RB8RUh8jzp2xx5ra+VydSXbnrmOzUrdw8kyk3rDLjYPAU3Q42aZ0961X+I6k+tL9HOkc/itQSoOenvlw9oqlbd0LIRCoz2J7qg4NZ7/cFSxQ6kVtT9mAObyaWfqwD9aKwrraFRJyIu5HM5aEOlkU9aIY0qxPaDlRdZSSWORQwXOsu9600v08HwqLNOkmLpVeE3M94KLA9790Nmu2ttZXLiGRXxCKLbWRJFZm6VLHMIv695m0BkHS9SLbCxhSBfj9VU8R2C5excMhafbyF38OnflRXdtNa3su6bJeD3HNwjvV13LXT7dZTnAXbATeZf90Za1N93t6IErkUHZknOUn4KfBrS/aD6kBe0of4qGii/71/Bs="
  bucket: cc.andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  #upload_dir: .
