language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "NNiRVtxVuHCnLcW4bbRqrcZOI5BeQX5EvIK/tu2qr6G0WO0+zE3bMyCVAs84RKtMwCOi7TqGCcWRnkB2GjylLLO1PKjhUSKdBzGcO2CO8ELeaMCU9aEckb1rdinyhi02keaQABRMAmpQOIdj2oQszl3ikSVWoZY3LpmdFaKUzxI0TVMSqKe/9hOatIUIVUfAs36Rv3C87i2MzS55yi9v8r6zDss4lK+20aN1iu+FHXVXbflZ1Zj4B5PFNGfjymZEMyJzNpnfZJIlVuJAJA2rGvvqzjBdSNdyiLszKAuam3bMLeJ1EBJnM+xEMglSy1O5tYwbZry8vnu+izKn3CgmrwY6H0g1SEsNXRWrTFBuJX+agzOPbO5c8RL2nFAWcd9aXh1+98127ROEywf8yAZVQNjCNt/Q5CH9HwvJiqMnccZ5LN3twSDcgsWb/W4bbkSNeDepMgzhnHXYyMzwlhv/cB0LZwQPfLmuewK/cJTXQc+J/FINoZhQluRKagTLK1NQxInI9Asn9LKCwkDb0Zgc9Lzh4KVFKMjvIpeKdQX1LY4Z9bl4UANEb+egLrkiiHDgXnKZQMiPTD/aWhuYJxmMFRsV1Dx6YVvRouR76Z+ISPo5kD+so0+qCt5ebtKMN6TJv9BqsIY4eYteRrvleYjQk4IJXCU2mdQGt0o2ECU7qik="
  secret_access_key:
    secure: "CU9cqgXbCucLvmGGloCR7j3eO/Qi/lPUvcp4Oj7LBt99Lf3wUU4WV6Q5q5pzv3XGuzddS+7fDae19onkk4GFmGS8bEV+P+wCh9kGUtNGq0A1+4wmW7H5NgAFv6yiJM6dzshNFUkO6a69E6tQ94U9y5FNtVpDX/j8rz9ha3JIuYj3al06zGZ8cX469g2ef90/dsgm0qRXl6be3Mh3r+gkZl65uIzx+o4VMhRTTenkxDt9eORmv12KE4Obvsn+xHwU9TQBd2lumz896yQwfVxn8O1V02e1a1AWrFiRAm9SWCVreNOPnmmpHSVSkxo89zNmw56eZdz59kfIfEfOO8kKhFEToHk5KO15cm8B0pYhhA/82iQOkY5ARO9zLYuuaEAfMM5pyp9Bsex9f+utQLSOVOylBtBl6L5xX+MxfQEe277iBzX/+OrF/zcJKPPi0Z24s3HHD2k4WZQUZy5U9ItaRKvSwiKycCKigJzqZ3dmAoxl6SqQDUmkq2MZmuDRtFKvK2RT86CwEPA7qLqSiO5Ki1NPywNwR+7i8FHZac37zXb7kqFONaKMJ6vDVj4bhkvN/FdEkQsOnM/AC2G7oGDTb6vTP6ImWuwRAk6xnLWhopfjMC+QBO4hEg0UMW53ohxlJXIiqxBAl6dSv5XIPiEXSsyqCYU+RSvd1nYS1N7hbdQ="
  bucket: cc.andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  #upload_dir: .
